# intents.py

intents = {
    # --- Browsers ---
    "open_browser_youtube": ["Open YouTube", "Go to YouTube", "Launch YouTube", "Hey FREDiie open YouTube pls", "Take me to YouTube", "Take me to the YouTube site",
                             "Youtube site pls", "Play videos on YouTube", "Open YT", "YT website", "Head to YouTube"],
    "open_browser_google": ["Open Google", "Search Google", "Hey FREDiie go to Google", "Google search pls", "Bring up Google", "Launch Google for me pls",
                            "Go Google", "Access Google site", "Open my Google", "Start Google", "Head over to Google"],
    "open_browser_chrome": ["Open Chrome", "Launch Chrome", "Hey FREDiie start Chrome pls", "Bring up Chrome", "Start my Chrome", "Hey FRED! launch Chrome browser", "Start Google Chrome app",
                            "Open Google Chrome", "Fire up Chrome", "Head to Chrome browser", "Access Chrome", "Open Chrome browser"],
    "open_browser_edge": ["Open Edge", "Launch Edge", "Hey freddie bring up edge", "Start Edge", "Hey FREDiie Edge pls", "Bring up Edge", "Hey FRED! bring up Edge", "Microsoft Edge pls",
                          "Fire up Edge", "Access Edge browser", "Head over to Edge", "Start Edge now"],
    "open_browser_gmail": ["Open Gmail", "Launch Gmail", "Hey FREDiie Gmail pls", "Bring up Gmail", "Check my Gmail",
                           "Go to Gmail", "Hey FRED, start Gmail" "Access Gmail", "Start Gmail", "Head to Gmail", "Open Gmail site"],
    "open_browser_chatgpt": ["Open ChatGPT", "Launch ChatGPT", "Hey FREDiie ChatGPT pls", "Start ChatGPT", "Bring up ChatGPT",
                             "Access ChatGPT", "Pull up ChatGPT pls", "Head to ChatGPT", "Open AI chat", "Start ChatGPT website", "Launch ChatGPT site"],
    "open_browser_discord": ["Open Discord", "Launch Discord", "Hey FREDiie Discord pls", "Start Discord", "Bring up Discord",
                             "Access Discord", "Pull up Discord pls", "Head to Discord", "Open my Discord", "Start Discord app", "Launch Discord app"],
    "open_browser_spotify": ["Open Spotify", "Launch Spotify", "Hey FREDiie Spotify pls", "Start Spotify", "Bring up Spotify",
                             "Access Spotify", "Head to Spotify", "Play music Spotify", "Start Spotify app", "Launch Spotify app"],
    "open_browser_amazon": ["Open Amazon", "Launch Amazon", "Hey FREDiie Amazon pls", "Start Amazon", "Bring up Amazon",
                            "Access Amazon", "Head to Amazon", "Shop Amazon", "Open Amazon site", "Launch Amazon online"],
    "open_browser_allen": ["Open Allen.in", "Launch Allen.in", "Hey FREDiie Allen pls", "Start Allen.in", "Bring up Allen.in",
                           "Access Allen.in", "Head to Allen", "Open Allen website", "Start Allen site", "Launch Allen online"],

    # --- System Apps ---
    "open_app_notepad": ["Open Notepad", "Hey FRED! start my Notepad", "Hey FREDiie Notepad pls", "Start Notepad", "Bring up Notepad", "Launch Notepad app",
                         "Run Notepad", "Fire up Notepad", "Open my Notepad", "Start Notepad app", "Open Notepad application"],
    "open_app_vscode": ["Open VS Code", "bring up Visual Studio Code for me please", "Hey FREDiie VS Code pls", "Launch VS Code", "Start VS Code", "Bring up VS Code",
                        "Run VS Code", "Fire up VS Code", "Open Visual Studio Code", "Start VSCode editor", "Launch VS Code editor"],
    "open_app_calculator": ["Open Calculator", "Hey FREDiie calc pls", "Launch Calculator", "Start Calculator", "Bring up Calculator",
                            "Run Calculator", "Fire up calc", "Access Calculator", "Start calc", "Launch calc"],
    "open_app_word": ["Open Word", "Hey FREDiie Word pls", "Start Word", "Launch Word", "Bring up Word",
                      "Run Word", "Fire up Word", "Open Microsoft Word", "Start Word app", "Launch Word editor"],
    "open_app_excel": ["Open Excel", "Hey FREDiie Excel pls", "Start Excel", "Launch Excel", "Bring up Excel",
                       "Run Excel", "Fire up Excel", "Open Microsoft Excel", "Start Excel app", "Launch Excel editor"],
    "open_app_powerpoint": ["Open PowerPoint", "Hey FREDiie PowerPoint pls", "Launch PowerPoint", "Start PowerPoint",
                            "Bring up PowerPoint", "Run PowerPoint", "Fire up PowerPoint", "Open MS PowerPoint",
                            "Start PowerPoint app", "Launch PowerPoint editor"],
    "open_app_paint": ["Open Paint", "Hey FREDiie Paint pls", "Launch Paint", "Start Paint", "Bring up Paint",
                       "Run Paint", "Fire up Paint", "Open MS Paint", "Start Paint app", "Launch Paint editor"],
    "open_app_cmd": ["Open CMD", "Hey FREDiie CMD pls", "Launch CMD", "Start CMD", "Bring up CMD",
                     "Run command prompt", "Start CMD terminal", "Open CMD app", "Fire up CMD", "Access CMD"],
    "open_app_clock": ["Open Clock", "Hey FREDiie Clock pls", "Launch Clock", "Start Clock", "Bring up Clock",
                       "Run Clock app", "Open Windows Clock", "Hey FRED! Start Clock pls", "Start Clock application", "Fire up Clock", "Bring up Clock app"],
    "open_app_settings": ["Open Settings", "Hey FRED! Settings pls", "Hey FRED, start Settings window", "Launch Settings", "Start Settings", "Pull up system settings pls",
                          "Bring up Settings", "Run Settings app", "Open Windows Settings", "Start Settings window",
                          "Fire up Settings", "Access Settings"],

    # --- Games / Dev ---
    "open_app_steam": ["Open Steam", "Hey FREDiie Steam pls", "Launch Steam", "Start Steam", "Bring up Steam",
                       "Run Steam", "Fire up Steam", "Open my Steam", "Bring up Steam platform pls", "Pull up Steam pls", "Start Steam app", "Launch Steam pls", "Hey FRED, start Steam app"],
    "open_app_forza": ["Open Forza", "Hey FREDiie Forza pls", "Launch Forza", "Start Forza", "Bring up Forza",
                       "Run Forza", "Fire up Forza", "Open my Forza", "Start Forza game", "Launch Forza app"],
    "open_app_lmstudio": ["Open LM Studio", "Hey FREDiie LM Studio pls", "Launch LM Studio", "Start LM Studio",
                           "Bring up LM Studio", "Run LM Studio", "Fire up LM Studio", "Open LM Studio editor",
                           "Start LM Studio app", "Launch LM Studio software"],
    "open_app_unity": ["Open Unity", "Hey FREDiie Unity pls", "Launch Unity", "Start Unity", "Bring up Unity",
                       "Run Unity", "Fire up Unity", "Open Unity Hub", "Start Unity editor", "Launch Unity software"],
    "open_app_godot": ["Open Godot", "Hey FREDiie Godot pls", "Launch Godot", "Start Godot", "Bring up Godot",
                       "Run Godot", "Fire up Godot", "Open Godot engine", "Start Godot editor", "Launch Godot software"],
    "open_app_davinci_resolve": ["Open Resolve", "Hey FREDiie Resolve pls", "Launch Resolve", "Start DaVinci Resolve",
                                 "Bring up Resolve", "Run Resolve", "Fire up Resolve", "Open DaVinci software",
                                 "Start Resolve editor", "Launch Resolve app"],
    "open_app_lively": ["Open Lively", "Hey FREDiie Lively pls", "Launch Lively Wallpaper", "Start Lively",
                        "Bring up Lively", "Run Lively", "Fire up Lively", "Start Lively app", "Open Lively Wallpaper", "Launch Lively"],

    # --- File Operations ---
    "create_text_file": ["Create a text file called groceries with milk and eggs", "Hey FREDiie make file tasks with homework",
                         "New text file called reminders with water and workout", "Write a file called ideas with new project", "Create file notes with random idea",
                         "Generate a file ideas.txt with project plan", "Make a file journal with daily notes",
                         "Write a text file todo.txt with tasks", "Create file shopping with apples and oranges",
                         "Start a text file games with gta and forza", "Please make a file plans with tasks", "Hey FRED, make a folder named Games"],
    "create_folder": ["Create a folder called Projects", "Hey FREDiie make folder Games", "New folder called Music",
                      "Generate folder Videos", "Start a folder Documents", "Please create folder Temp",
                      "Write a folder named Backups", "Create folder Downloads", "Make folder UnityProjects",
                      "Generate folder Work"],

    # --- Normal Conversation (50 casual) ---
    "chat": [
        "Hey FREDiie", "Hello Freddie", "Yo FRED", "Hi Fred", "Sup FREDdie", "Hello FRED", "FRED pls", "Hey buddy", "Yo", "Hey", "Hi", "Hello",
        "What's up", "How r u?", "Hey FRED whatsup?", "Freddie", "FRED hey", "Hello", "Heyy FREDdie", "Yo Fred", "Hiya",
        "Hey Freddie u there?", "Whats good?", "Heyo", "Freddie hi", "Hey FREDiie wazzup", "Yo FREDiie", "Hi FRED",
        "Hey FREDiie wassup", "Fred wassup", "Hello there", "Hi Fredie", "Hey Fredie", "Yo FRED wassup", "Hey FREDiie pls",
        "Hey Fred wazzup", "Hi Fred wazzup", "FRED how r u", "Hey FREDiie u good", "Yo Fredie", "Hey buddy FRED", "Hi FREDiie",
        "Hey Frediie", "Yo FREDiie wassup", "Hey Fredie pls", "Hi Frediie", "FREDiie", "Hey FREDiie hi", "Yo Fred wassup",
        "Do u remember my age?", "Do u remember my weight?", "Do u know what a v taper is?", "Who are u?", "I am integrating TTS into U!", "I am currently in Phase 8!", "Do u know JARVIS?", "I am 62 kg at 5 10 height"
    ]
}