# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for FRED GUI application

a = Analysis(
    ['fred_gui.py'],
    pathex=['Core'],
    binaries=[],
    datas=[
        ('Core/models', 'models'),
        ('Core/config', 'config'),
        ('Core/personality', 'personality'),
        ('Core/ui', 'ui'),
        ('Core/orchestrator', 'orchestrator'),
        ('Core/audio', 'audio'),
        ('Core/llm', 'llm'),
        ('Core/memory', 'memory'),
        ('Core/state', 'state'),
        ('Core/tools', 'tools'),
        ('Core/utils', 'utils'),
    ],
    hiddenimports=[
        'tkinter',
        'queue',
        'threading',
        'orchestrator.orchestrator',
        'orchestrator.dispatcher',
        'orchestrator.scheduler',
        'ui.hud',
        'ui.gui_app',
        'llm.llm_client',
        'memory.memory_manager',
        'state.conversation_state',
        'tools.registry',
        'tools.system_tools',
        'tools.web_tools',
        'tools.machine_tools',
        'audio.device_info',
        'audio.stt',
        'audio.tts',
        'audio.wake_word',
        'utils.gpu_bootstrap',
        'utils.notifier',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludedimports=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FRED',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
